# Generated by Django 6.0.3 on 2026-03-12 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='recorrente'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia de recorrência'),
        ),
    ]
